import { describe, it, expect } from 'vitest';
import { LineAssembler, checkUnsupportedArchive } from './byteStream';
import { detectHeaderColumns, sniffDelimiter, detectVendorAndChip } from './formatSniffer';
import { decodeVcfGenotype, parseVcfLine } from './vcfTokenizer';
import { cleanGenotypeString, parseLineBytes, parseAdaptiveLine } from './tabularTokenizer';
import { parseRawDNA, parseRawDNAStream } from './engine';
import { GenomicsErrorCode } from '../errorCaller';
import { zipSync } from 'fflate';

describe('Rebuilt Parser Engine — Micro-benchmarks & Edge Seams', () => {
  it('should correctly assemble lines split across arbitrary tiny byte chunks without data corruption', () => {
    const assembler = new LineAssembler();
    const fullText = `rs1\t1\t100\tAA\nrs2\t1\t200\tGG\r\nrs3\t1\t300\tCC\nrs4\t1\t400\tTT`;
    const encoder = new TextEncoder();
    const bytes = encoder.encode(fullText);

    const emittedLines: string[] = [];
    // Slice into tiny 3-byte chunks to stress test chunk boundary handling
    const CHUNK_SIZE = 3;
    for (let i = 0; i < bytes.length; i += CHUNK_SIZE) {
      const chunk = bytes.subarray(i, Math.min(i + CHUNK_SIZE, bytes.length));
      for (const line of assembler.pushChunk(chunk)) {
        emittedLines.push(new TextDecoder().decode(line));
      }
    }
    for (const line of assembler.flush()) {
      emittedLines.push(new TextDecoder().decode(line));
    }

    expect(emittedLines).toEqual([
      'rs1\t1\t100\tAA',
      'rs2\t1\t200\tGG',
      'rs3\t1\t300\tCC',
      'rs4\t1\t400\tTT'
    ]);
  });

  it('should handle CRLF split directly between \\r and \\n across chunk boundaries', () => {
    const assembler = new LineAssembler();
    const encoder = new TextEncoder();

    // Chunk 1 ends with \r
    const chunk1 = encoder.encode('rs100\t1\t1000\tAG\r');
    // Chunk 2 begins with \n
    const chunk2 = encoder.encode('\nrs200\t1\t2000\tCT\n');

    const emittedLines: string[] = [];
    for (const line of assembler.pushChunk(chunk1)) {
      emittedLines.push(new TextDecoder().decode(line));
    }
    for (const line of assembler.pushChunk(chunk2)) {
      emittedLines.push(new TextDecoder().decode(line));
    }
    for (const line of assembler.flush()) {
      emittedLines.push(new TextDecoder().decode(line));
    }

    expect(emittedLines).toEqual([
      'rs100\t1\t1000\tAG',
      'rs200\t1\t2000\tCT'
    ]);
  });

  it('should decode multiallelic and phased genotypes accurately', () => {
    // REF=A, ALT=C,T, GT=1/2 -> CT
    const multi = decodeVcfGenotype('A', 'C,T', '1/2');
    expect(multi).toBeDefined();
    expect(multi?.genotype).toBe('CT');
    expect(multi?.isPhased).toBe(false);

    // Phased GT=0|1 -> A|G
    const phased = decodeVcfGenotype('A', 'G', '0|1', '100');
    expect(phased).toBeDefined();
    expect(phased?.genotype).toBe('AG');
    expect(phased?.isPhased).toBe(true);
    expect(phased?.allele1).toBe('A');
    expect(phased?.allele2).toBe('G');
    expect(phased?.phaseSet).toBe('100');
  });

  it('should stream parse VCF with dot (.) IDs using dual coordinate allowlist keys', async () => {
    const vcfContent = `##fileformat=VCFv4.2
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
1\t500100\t.\tA\tC\t99\tPASS\t.\tGT\t0/1
2\t600200\t.\tG\tT\t99\tPASS\t.\tGT\t1/1
`;
    const file = new Blob([vcfContent]);
    const allowlist = new Set<string>(['chr1_500100', '2_600200']);

    const parsed = await parseRawDNAStream(file, allowlist);
    expect(parsed.snpCount).toBe(2);
    expect(parsed.snpMap['chr1_500100']).toBe('AC');
    expect(parsed.snpMap['chr2_600200']).toBe('TT');
  });

  it('should cleanly reject unsupported archive formats with structured error codes', () => {
    const sevenZipBytes = new Uint8Array([0x37, 0x7a, 0xbc, 0xaf, 0x27, 0x1c, 0x00]);
    expect(() => checkUnsupportedArchive(sevenZipBytes)).toThrow(/Unsupported 7-Zip/);

    const rarBytes = new Uint8Array([0x52, 0x61, 0x72, 0x21, 0x1a, 0x07]);
    expect(() => checkUnsupportedArchive(rarBytes)).toThrow(/Unsupported RAR/);
  });

  it('should stream parse 150,000 SNPs in seconds with continuous progress heartbeats and inline snpByPosition', async () => {
    const lines: string[] = [
      '# This data file generated by 23andMe at: Tue Sep 20 12:00:00 2026',
      '# rsid\tchromosome\tposition\tgenotype'
    ];
    for (let i = 1; i <= 150000; i++) {
      lines.push(`rs${i}\t${(i % 22) + 1}\t${i * 100}\tAG`);
    }
    const rawBytes = new TextEncoder().encode(lines.join('\n'));
    const file = new Blob([rawBytes]);

    let progressCallbacks = 0;
    const start = performance.now();
    const parsed = await parseRawDNAStream(file, undefined, () => {
      progressCallbacks++;
    });
    const elapsed = performance.now() - start;

    expect(parsed.snpCount).toBe(150000);
    expect(progressCallbacks).toBeGreaterThan(5);
    expect(parsed.snpByPosition['2:100']).toBe('AG');
    expect(Object.keys(parsed.snpByPosition).length).toBe(150000);
    expect(elapsed).toBeLessThan(5000);
  });

  it('should stream parse a compressed ZIP archive of 100,000 SNPs under 3 seconds without freezing', async () => {
    const lines: string[] = [
      '# This data file generated by AncestryDNA',
      '# rsid\tchromosome\tposition\tallele1\tallele2'
    ];
    for (let i = 1; i <= 100000; i++) {
      lines.push(`rs${i}\t${(i % 22) + 1}\t${i * 100}\tA\tG`);
    }
    const rawBytes = new TextEncoder().encode(lines.join('\n'));
    const zipBytes = zipSync({
      'dna_data.txt': rawBytes,
      'README.txt': new TextEncoder().encode('Read me instructions')
    });
    const zipBlob = new Blob([zipBytes]);

    let progressCallbacks = 0;
    const start = performance.now();
    const parsed = await parseRawDNAStream(zipBlob, undefined, () => {
      progressCallbacks++;
    });
    const elapsed = performance.now() - start;

    expect(parsed.snpCount).toBe(100000);
    expect(progressCallbacks).toBeGreaterThan(3);
    expect(parsed.snpByPosition['2:100']).toBe('AG');
    expect(Object.keys(parsed.snpByPosition).length).toBe(100000);
    expect(elapsed).toBeLessThan(5000);
  });
});

